name: peron_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  dotted_border: ^2.0.0
  cached_network_image:
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.0+3
  circular_reveal_animation: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.7
  country_pickers:
  flutter_libphonenumber: ^2.5.1
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0
  country_code_picker: ^3.2.0
  animated_bottom_navigation_bar: ^1.4.0
  font_awesome_flutter: ^10.8.0
  material_symbols_icons: ^4.2808.1
  provider:
  shimmer:
  google_maps_flutter: ^2.10.1
  geolocator:
  table_calendar: ^3.0.9
  permission_handler: ^11.4.0
  geocoding: ^2.0.0
  location:
  shared_preferences:
  flutter_otp_text_field: ^1.5.1+1
  collection: ^1.19.1
  get_it:
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  intl: ^0.19.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_foreground: "assets/icons/logo.png"
  adaptive_icon_background: "assets/icons/empty.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # تحديث الإصدار

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
